apiVersion: edna.graitdm.edu/v1
kind: EdnaJob
metadata:
  name: job2
spec:
  import_key: none
  export_key: out-topic
  jobname: SinkJob
  applicationname: tony-examples
  filename: SinkJob
  jobcontext: ednaconf
  jobtype: internal
  jobimagetag: latest
  registryhost: localhost
  registryport: 5000
  jobvariablenames:
    - import_key
  jobvariablevalues:
    - out-topic
