template:
    applicationname: kafkasimple
    jobname: internal-job
    filename: InternalJob
    jobcontext: ednaconf
    jobreplicas: 1
    jobtype: internal
    jobimage: 
      registryaddress: localhost:5000
      imagetag: latest
    jobgraph:
      import_key: "source-job-stream"
      export_key: "job1-stream"
    jobvariables:
      import_topic: "source-job-stream"
      import_key: "job1-stream"