apiVersion: edna.graitdm.edu/v1
kind: EdnaJob
metadata:
  name: sink-job
spec:
  import_key: job1-stream
  export_key: job1-stream
  jobname: sink-job
  applicationname: kafkasimple
  filename: SinkJob
  jobcontext: ednaconf
  jobtype: internal
  jobimagetag: latest
  registryhost: localhost
  registryport: 5000
  jobvariablenames:
    - bootstrap_server
  jobvariablevalues:
    - "edna-cluster-kafka-bootstrap.kafka.svc.cluster.local"
