template:
    applicationname: kafkasimple
    jobname: sink-job
    filename: SinkJob
    jobcontext: ednaconf
    jobreplicas: 1
    jobtype: internal
    jobimage: 
      registryaddress: localhost:5000
      imagetag: latest
    jobgraph:
      import_key: "job1-stream"
      export_key: "out-topic"
    jobvariables:
      import_topic: "job1-stream"
      import_key: "out-topic"