apiVersion: edna.graitdm.edu/v1
kind: EdnaJob
metadata:
  name: job2
spec:
  import_key: job1-stream
  export_key: out-topic
  jobname: sink-job
  applicationname: kafka-application-example
  filename: SinkJob
  jobcontext: ednaconf
  jobtype: internal
  jobimagetag: latest
  registryhost: localhost
  registryport: 5000
  jobvariablenames:
    - import_key
    - export_key
  jobvariablevalues:
    - job1-stream
    - out-topic
