apiVersion: edna.graitdm.edu/v1
kind: EdnaJob
metadata:
  name: job2
spec:
  import_key: source-job-stream
  export_key: job1-stream
  jobname: internal-job
  applicationname: kafkasimple
  filename: InternalJob
  jobcontext: ednaconf
  jobtype: internal
  jobimagetag: latest
  registryhost: localhost
  registryport: 5000
  jobvariablenames:
    - import_key
    - export_key
  jobvariablevalues:
    - source-job-stream
    - job1-stream
